import Head from 'next/head'

import { Inter } from 'next/font/google'
import { useState, useEffect } from 'react'


const API_URL="https://api.exchangerate-api.com/v4/latest/"
const userBalance =[
  {currency:"GBP", balance:2000},
  {currency:"UR", balance:3500},
  {currency:"NGN", balance:200000},
  ]
  
  const prevData = userBalance[2]
export default function Home() {
  const [bal, setBal]= useState(prevData)
  const [fromInput, setFromInput] = useState(0)
  const [outputInput, setOutInput] = useState(0)
  const [showOptions, setShowOptions] = useState(false)

  const [prevCurr, setPrevCurr]=useState({
  prev:prevData.currency,
  curr:null
  })
  const [showOptionsOut, setShowOptionsOut] = useState(false)
  const handleChange=(e)=>{
    setFromInput(e.target.value)
  }
  const handleSwitch=(val, walletType)=>{
    setPrevCurr(()=>({
      prev:"",
      // curr:""
    }))
    if(walletType==="from"){      
          setBal(val)
          setShowOptions(state =>!state)
          return;
    }

    setShowOptionsOut(state =>!state)

  }
 const currentCurr =bal.currency
  useEffect(()=>{
    if(fromInput===0){
      return;
    }
  const fetchData = async()=>{    const result = await fetch(`${API_URL}${currentCurr}`).then(info=>info.json())
    console.log(result, "reslt")

  }

  fetchData()
  },[currentCurr, fromInput])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
       
       <div className="exchange-comp flex">
        <div className="">
       <h1 className="title">
    Convert from one to another Currency
        </h1>   
    <div className="input-card from-div">
    <div className='flex align-items-center justify-between wallet-section'>
      <div className="currency-options">
        <div className="flex" onClick={()=>setShowOptions(state=>!state)}>
          {bal.currency} Wallet
        <div className="angle-down">
          {">"}
        </div>
        </div>

       {
        showOptions &&   <div>
        <ul className="currency-list">
          {
            userBalance.map((bal, index)=>{
              return   <li onClick={()=>handleSwitch(bal, "from")} className={`${index===0 ? "first-li":""}`} key={bal.currency}>
                {bal.currency}
              </li>
            })
          }
        </ul>
      </div>
       }
  
      </div>
      <div>
        <div className="user-bal">Balance</div>
        {bal.balance}
      </div>
    </div>
    <div>
      <input value={fromInput} name="from" onClick={handleChange} className='w-100 input-el' />
    </div>
    </div>

    <div className="input-card output-div">
    <div className='flex align-items-center justify-between wallet-section'>
      <div className="currency-options">
        <div className="flex" onClick={()=>setShowOptions(state=>!state)}>
          Convert to
        <div className="angle-down">
          {">"}
        </div>
        </div>

       {
        showOptionsOut &&   <div>
        <ul className="currency-list">
          {
            userBalance.map((bal, index)=>{
              return   <li onClick={()=>handleSwitch(bal,"output")} className={`${index===0 ? "first-li":""}`} key={bal.currency}>
                {bal.currency}
              </li>
            })
          }
        </ul>
      </div>
       }
  
      </div>
      <div>
        <div className="user-bal">Balance</div>      
        0
      </div>
    </div>
    <div>
      <input disabled value={outputInput} name="from"  className='w-100 input-el' />
    </div>
    </div>

          
       

        </div>
        <div className="preview">Preview</div>
       </div>
    
      </main>
    </>
  )
}
